default_environment: default
environments:
    default:
        connections:
            duckdb:
                - name: duckdb-default
                  path: duckdb.db
                - name: default
                  path: duckdb.db
            google_cloud_platform:
                - name: gcp-default
                  project_id: bruin-playground-bahar
                  use_application_default_credentials: true
