default_environment: default
environments:
    default:
        connections:
            duckdb:
                - name: duckdb-default
                  path: duckdb.db
                - name: default
                  path: duckdb.db
